vehshop = {
	opened = false,
	title = "HazeRP Bilforhandler",
	currentmenu = "main",
	lastmenu = nil,
	currentpos = nil,
	selectedbutton = 0,
	marker = { r = 0, g = 155, b = 255, a = 200, type = 1 },
	menu = {
		x = 0.1,
		y = 0.08,
		width = 0.2,
		height = 0.04,
		buttons = 10,
		from = 1,
		to = 10,
		scale = 0.4,
		font = 0,
		["main"] = {
			title = "Showroom",
			name = "main",
			buttons = {
				{name = "Eksklusiv", description = ''},
				{name = "Kompakte", description = ''},
				{name = "Coupéer", description = ''},
				{name = "Sedan", description = ''},
				{name = "Sports", description = ''},
				{name = "Sport klassikere", description = ''},
				{name = "Supers", description = ''},
				{name = "Muskel", description = ''},
				{name = "Offroad", description = ''},
				{name = "SUVer", description = ''},
				{name = "Varevogne", description = ''},
				{name = "Motorcykler", description = ''},
			}
		},
		["Eksklusiv"] = {
			title = "Eksklusiv",
			name = "Eksklusiv",
			buttons = {
				{name = "Lamborghini Performante", costs = 7000000, description = {}, model = "18performante"},
				{name = "Ferrari 599 Gtox", costs = 2000000, description = {}, model = "599gtox"},
				{name = "Porsche 718 Boxster", costs = 2500000, description = {}, model = "718boxster"},
				{name = "Brabus 850", costs = 50000000, description = {}, model = "brabus850"},
				{name = "Porsche 911 Turbo S", costs = 4000000, description = {}, model = "911turbos"},
				{name = "Bugatti Chiron", costs = 8000000, description = {}, model = ""},
				{name = "Mercedes A45 AMG", costs = 700000, description = {}, model = "a45amg"},
				{name = "Koenigsegg Agera", costs = 9000000, description = {}, model = "acsr"},
				{name = "Ferrari Aperta", costs = 6000000, description = {}, model = "aperta"},
				{name = "Audi S8", costs = 1000000, description = {}, model = "audis8om"},
				{name = "Pagani", costs = 7000000, description = {}, model = "bc"},
				{name = "Bugatti Divo", costs = 15000000, description = {}, model = "bdivo"},
				{name = "Mercedes Sl63", costs = 2000000, description = {}, model = "benzsl63"},
				{name = "BMW M5", costs = 1000000, description = {}, model = "bmci"},
				{name = "BMW s1000", costs = 16000000, description = {}, model = "bmws"},
				{name = "Bugatti Veyron", costs = 8000000, description = {}, model = "bugatti"},
				{name = "Corvette C7", costs = 3000000, description = {}, model = "c7"},
				{name = "Corvette C8", costs = 7000000, description = {}, model = "c8"},
				{name = "Mercedes C63s", costs = 10000000, description = {}, model = "c63s"},
				{name = "Ford GT 1968", costs = 2000000, description = {}, model = "fgt"},
				{name = "Ferrari Fxxk", costs = 5000000, description = {}, model = "fxxk"},
				{name = "Mercedes G63 AMG", costs = 1000000, description = {}, model = "g63amg"},
				{name = "Gardenshed", costs = 50000, description = {}, model = "gardenshed"},
				{name = "Mercedes GTR", costs = 6000000, description = {}, model = "gtrc"},
				{name = "Nissan GTR GT3", costs = 5000000, description = {}, model = "gtrgt3"},
				{name = "BMW i8", costs = 3000000, description = {}, model = "i8"},
				{name = "Hummer", costs = 1500000, description = {}, model = "h2m"},
				{name = "Isetta", costs = 30000, description = {}, model = "isetta"},
				{name = "Koenigsegg Jerka", costs = 9000000, description = {}, model = "jes"},
				{name = "Lexus", costs = 1000000, description = {}, model = "lc500"},
				{name = "Lamborghini LP700", costs = 8000000, description = {}, model = "lp700"},
				{name = "Lykan Hypersport", costs = 7000000, description = {}, model = "lykan"},
				{name = "BMW M6", costs = 6000000, description = {}, model = "m6f13"},
				{name = "Kawasaki", costs = 3000000, description = {}, model = "nh2r"},
				{name = "Randers knallert", costs = 30000, description = {}, model = "nrg"},
				{name = "McLaren P1", costs = 10000000, description = {}, model = "p1"},
				{name = "Porsche Panamera Turbo", costs = 2500000, description = {}, model = "panamera17turbo"},
				{name = "Audi R8", costs = 6000000, description = {}, model = "r820"},
				{name = "Mercedes GT63 Coupe", costs = 14000000, description = {}, model = "rmodgt63"},
				{name = "BMW M4", costs = 700000, description = {}, model = "rmodm4gts"},
				{name = "Mustang GT", costs = 1800000, description = {}, model = "rmodmustang"},
				{name = "Lamborghini Veneno", costs = 7000000, description = {}, model = "rmodveneno"},
				{name = "Audi RS6", costs = 1600000, description = {}, model = "rs615"},
				{name = "Mercedes S500 W222", costs = 20000000, description = {}, model = "s500w222"},
				{name = "Lamborghini SC18", costs = 11000000, description = {}, model = "sc18"},
				{name = "Mercedes E63", costs = 5000000, description = {}, model = "schafter3"},
				{name = "McLaren Senna", costs = 17000000, description = {}, model = "senna"},
				{name = "Lamborghini Sesto", costs = 10000000, description = {}, model = "sesto"},
				{name = "Lamborghini Sian", costs = 7000000, description = {}, model = "sian2"},
				{name = "Mercedes SLS AMG", costs = 3000000, description = {}, model = "slsamg"},
				{name = "Audi SQ7", costs = 6000000, description = {}, model = "sq72016"},
				{name = "Toyota Supra", costs = 2000000, description = {}, model = "supra2"},
				{name = "Tesla Model X", costs = 1500000, description = {}, model = "teslax"},
				{name = "Lamborghini Urus", costs = 13000000, description = {}, model = "urus2018"},
				{name = "Dodge Viper", costs = 455000, description = {}, model = "viper"},
				{name = "Lada", costs = 1000, description = {}, model = "urban"},
			}
		},
		["Kompakte"] = {
			title = "Kompakte",
			name = "Kompakte",
			buttons = {
				{name = "Blista", costs = 50000, description = {}, model = "blista"},
				{name = "Blista Compact", costs = 40000, description = {}, model = "blista2"},
				{name = "Brioso R/A", costs = 75000, description = {}, model = "brioso"},
				{name = "Dilettante", costs = 50000, description = {}, model = "Dilettante"},
				{name = "Issi", costs = 60000, description = {}, model = "issi2"},
				{name = "Issi Classic", costs = 40000, description = {}, model = "issi3"},
				{name = "Panto", costs = 60000, description = {}, model = "panto"},
				{name = "Prairie", costs = 75000, description = {}, model = "prairie"},
				{name = "Rhapsody", costs = 50000, description = {}, model = "rhapsody"},
			}
		},
		["Coupéer"] = {
			title = "Coupéer",
			name = "Coupéer",
			buttons = {
				{name = "Specter", costs = 2700000, description = {}, model = "specter"},
				{name = "Specter CTM", costs = 2700000, description = {}, model = "specter2"},
				{name = "Cognoscenti Cabrio", costs = 2300000, description = {}, model = "cogcabrio"},
				{name = "F620", costs = 2300000, description = {}, model = "f620"},
				{name = "Felon GT", costs = 1900000, description = {}, model = "felon2"},
				{name = "Jackal", costs = 1600000, description = {}, model = "jackal"},
				{name = "Oracle", costs = 1600000, description = {}, model = "oracle"},
				{name = "Oracle XS", costs = 1700000, description = {}, model = "oracle2"},
				{name = "Sentinel", costs = 900000, description = {}, model = "sentinel"},
				{name = "Sentinel XS", costs = 900000, description = {}, model = "sentinel2"},
				{name = "Windsor", costs = 2000000, description = {}, model = "windsor"},
				{name = "Windsor Drop", costs = 2200000, description = {}, model = "windsor2"},
				{name = "Zion", costs = 1100000, description = {}, model = "zion"},
				{name = "Zion Cabrio", costs = 1300000, description = {}, model = "zion2"},
			}
		},
		["Sports"] = {
			title = "Sports",
			name = "Sports",
			buttons = {
                {name = "Neon", costs = 1500000, description = {}, model = "neon"},
                {name = "Comet SR", costs = 1145000, description = {}, model = "comet5"},
                {name = "Comet", costs = 550000, description = {}, model = "comet3"},
                {name = "Pariah", costs = 1420000, description = {}, model = "pariah"},
                {name = "Banshee", costs = 105000, description = {}, model = "banshee"},
                {name = "Bestia GTS", costs = 610000, description = {}, model = "bestiagts"},
                {name = "Buffalo", costs = 750000, description = {}, model = "buffalo"},
                {name = "Buffalo S", costs = 960000, description = {}, model = "buffalo2"},
                {name = "Carbonizzare", costs = 195000, description = {}, model = "carbonizzare"},
                {name = "Coquette", costs = 138000, description = {}, model = "coquette"},
                {name = "Drift Tampa", costs = 995000, description = {}, model = "tampa2"},
                {name = "Feltzer", costs = 145000, description = {}, model = "feltzer2"},
                {name = "Furore GT", costs = 448000, description = {}, model = "furoregt"},
                {name = "Fusilade", costs = 650000, description = {}, model = "fusilade"},
                {name = "Jester", costs = 240000, description = {}, model = "jester"},
                {name = "Jester(Racerbil)", costs = 350000, description = {}, model = "jester2"},
                {name = "Kuruma", costs = 126350, description = {}, model = "kuruma"},
                {name = "Lynx", costs = 1735000, description = {}, model = "lynx"},
                {name = "Massacro", costs = 275000, description = {}, model = "massacro"},
                {name = "Massacro(Racecar)", costs = 385000, description = {}, model = "massacro2"},
                {name = "Omnis", costs = 701000, description = {}, model = "omnis"},
                {name = "Penumbra", costs = 600000, description = {}, model = "penumbra"},
                {name = "Rapid GT", costs = 132000, description = {}, model = "rapidgt"},
                {name = "Rapid GT Convertible", costs = 140000, description = {}, model = "rapidgt2"},
                {name = "Surano", costs = 100000, description = {}, model = "surano"},
                {name = "Tropos", costs = 816000, description = {}, model = "tropos"},
                {name = "Verkierer", costs = 695000, description = {}, model = "verlierer2"},
                {name = "Schlagen GT", costs = 1300000, description = {}, model = "Schlagen"},
                {name = "Khamelion", costs = 100000, description = {}, model = "khamelion"},
                {name = "Raptor", costs = 648000, description = {}, model = "raptor"},
                {name = "Ruston", costs = 430000, description = {}, model = "ruston"},
                {name = "Dominator GTX", costs = 725000, description = {}, model = "dominator3"},
				{name = "Sultan RS", costs = 450000, description = {}, model = "sultanrs"},
 
			}
		},
		["Sport klassikere"] = {
			title = "Sport klassikere",
			name = "Sport klassikere",
			buttons = {
				{name = "Rapid GT", costs = 885000, description = {}, model = "rapidgt3"},
                {name = "Retinue", costs = 615000, description = {}, model = "retinue"},
                {name = "Torero", costs = 998000, description = {}, model = "torero"},
                {name = "Cheetah Classic", costs = 865000, description = {}, model = "cheetah2"},
                {name = "GT500", costs = 785000, description = {}, model = "gt500"},
                {name = "Hermes", costs = 535000, description = {}, model = "hermes"},
                {name = "Casco", costs = 904000, description = {}, model = "casco"},
                {name = "Coquette Classic", costs = 665000, description = {}, model = "coquette2"},
                {name = "Pigalle", costs = 400000, description = {}, model = "pigalle"},
                {name = "Stinger", costs = 850000, description = {}, model = "stinger"},
                {name = "Stinger GT", costs = 875000, description = {}, model = "stingergt"},
                {name = "Stirling GT", costs = 975000, description = {}, model = "feltzer3"},
                {name = "Z-Type", costs = 950000, description = {}, model = "ztype"},
			}
		},
		["Supers"] = {
			title = "Supers",
			name = "Supers",
			buttons = {
                {name = "Adder", costs = 1000000, description = {}, model = "adder"},
                {name = "Nero", costs = 1440000, description = {}, model = "nero"},
                {name = "Entity XF", costs = 795000, description = {}, model = "entityxf"},
                {name = "Entity XXR", costs = 2305000, description = {}, model = "entity2"},
                {name = "811", costs = 1135000, description = {}, model = "pfister811"},
                {name = "Cyclone", costs = 1890000, description = {}, model = "cyclone"},
                {name = "Reaper", costs = 1595000, description = {}, model = "reaper"},
                {name = "Tyrant", costs = 2515000, description = {}, model = "tyrant"},
			}
		},
		["Muskel"] = {
			title = "Muskel",
			name = "Muskel",
			buttons = {
				{name = "Blade", costs = 160000, description = {}, model = "blade"},
				{name = "Buccaneer", costs = 190000, description = {}, model = "buccaneer"},
				{name = "Chino", costs = 225000, description = {}, model = "chino"},
				{name = "Coquette BlackFin", costs = 695000, description = {}, model = "coquette3"},
				{name = "Dominator", costs = 350000, description = {}, model = "dominator"},
				{name = "Dukes", costs = 162000, description = {}, model = "dukes"},
				{name = "Hotknife", costs = 190000, description = {}, model = "hotknife"},
				{name = "Faction", costs = 136000, description = {}, model = "faction"},
				{name = "Nightshade", costs = 585000, description = {}, model = "nightshade"},
				{name = "Picador", costs = 100000, description = {}, model = "picador"},
				{name = "Sabre Turbo", costs = 500000, description = {}, model = "sabregt"},
				{name = "Tampa", costs = 375000, description = {}, model = "tampa"},
				{name = "Virgo", costs = 195000, description = {}, model = "virgo"},
			}
		},
		["Offroad"] = {
			title = "Offroad",
			name = "Offroad",
			buttons = {
				{name = "Kamacho", costs = 315000, description = {}, model = "kamacho"},
				{name = "Riata", costs = 325000, description = {}, model = "riata"},
				{name = "Streiter", costs = 235000, description = {}, model = "streiter"},
				{name = "Bifta", costs = 75000, description = {}, model = "bifta"},
				{name = "Blazer", costs = 10000, description = {}, model = "blazer"},
				{name = "Brawler", costs = 715000, description = {}, model = "brawler"},
				{name = "Bubsta 6x6", costs = 375000, description = {}, model = "dubsta3"},
				{name = "Dune Buggy", costs = 200000, description = {}, model = "dune"},
				{name = "Rebel", costs = 220000, description = {}, model = "rebel2"},
				{name = "Nagasaki Street Blazer", costs = 35000, description = {}, model = "blazer4"},
			}
		},
		["SUVer"] = {
			title = "SUVer",
			name = "SUVer",
			buttons = {
                {name = "Baller", costs = 60000, description = {}, model = "baller"},
                {name = "Baller 2", costs = 90000, description = {}, model = "baller2"},
                {name = "Baller LE", costs = 149000, description = {}, model = "baller3"},
                {name = "Dubsta", costs = 1245000, description = {}, model = "dubsta"},
                {name = "Dubsta 2", costs = 249000, description = {}, model = "dubsta2"},
                {name = "Toros", costs = 498000, description = {}, model = "toros"},
                {name = "Contender", costs = 250000, description = {}, model = "contender"},
                {name = "XLS", costs = 253000, description = {}, model = "xls"},
                {name = "Rocoto", costs = 85000, description = {}, model = "rocoto"},
			}
		},
		["Varevogne"] = {
			title = "Varevogne",
			name = "Varevogne",
			buttons = {
				{name = "Moonbeam", costs = 450000, description = {}, model = "moonbeam2"},
				{name = "Yosemite", costs = 285000, description = {}, model = "yosemite"},
				{name = "Bison", costs = 130000, description = {}, model = "bison"},
				{name = "Bobcat XL", costs = 123000, description = {}, model = "bobcatxl"},
				{name = "Gang Burrito", costs = 245000, description = {}, model = "gburrito"},
				{name = "Journey", costs = 150000, description = {}, model = "journey"},
				{name = "Minivan", costs = 300000, description = {}, model = "minivan"},
				{name = "Paradise", costs = 250000, description = {}, model = "paradise"},
				{name = "Rumpo", costs = 130000, description = {}, model = "rumpo"},
				{name = "Surfer", costs = 110000, description = {}, model = "surfer"},
				{name = "Youga", costs = 160000, description = {}, model = "youga"},
				{name = "Granger", costs = 315000, description = {}, model = "granger"},
			}
		},
		["Sedan"] = {
			title = "Sedan",
			name = "Sedan",
			buttons = {
				{name = "Raiden", costs = 2500000, description = {}, model = "raiden"},
				{name = "Asea", costs = 200000, description = {}, model = "asea"},
				{name = "Cognoscenti", costs = 2200000, description = {}, model = "cognoscenti"},
				{name = "Cognoscenti 55", costs = 2000000, description = {}, model = "cog55"},
				{name = "Glendale", costs = 400000, description = {}, model = "glendale"},
				{name = "Ingot", costs = 85000, description = {}, model = "ingot"},
				{name = "Intruder", costs = 120000, description = {}, model = "intruder"},
				{name = "Premier", costs = 150000, description = {}, model = "premier"},
				{name = "Primo", costs = 100000, description = {}, model = "primo"},
				{name = "Primo Custom", costs = 200000, description = {}, model = "primo2"},
				{name = "Regina", costs = 100000, description = {}, model = "regina"},
				{name = "Stanier", costs = 100000, description = {}, model = "stanier"},
				{name = "Stratum", costs = 100000, description = {}, model = "stratum"},
				{name = "Super Diamond", costs = 1250000, description = {}, model = "superd"},
				{name = "Surge", costs = 240000, description = {}, model = "surge"},
				{name = "Tailgater", costs = 600000, description = {}, model = "tailgate"},
				{name = "Warrener", costs = 320000, description = {}, model = "warrener"},
				{name = "Washington", costs = 150000, description = {}, model = "washingt"},
			}
		},
		["Motorcykler"] = {
			title = "Motorcykler",
			name = "Motorcykler",
			buttons = {
				{name = "Akuma", costs = 90000, description = {}, model = "AKUMA"},
				{name = "Bagger", costs = 50000, description = {}, model = "bagger"},
				{name = "Bati 801", costs = 150000, description = {}, model = "bati"},
				{name = "Bati 801RR", costs = 150000, description = {}, model = "bati2"},
				{name = "BF400", costs = 195000, description = {}, model = "bf400"},
				{name = "Carbon RS", costs = 180000, description = {}, model = "carbonrs"},
				{name = "Cliffhanger", costs = 325000, description = {}, model = "cliffhanger"},
				{name = "Double T", costs = 112000, description = {}, model = "double"},
				{name = "Faggio", costs = 14000, description = {}, model = "faggio2"},
				{name = "Knallert", costs = 18000, description = {}, model = "faggio"},
				{name = "Gargoyle", costs = 220000, description = {}, model = "gargoyle"},
				--{name = "Daemon", costs = 100000, description = {}, model = "daemon"},
				{name = "Innovation", costs = 190000, description = {}, model = "innovation"},
				{name = "PCJ-600", costs = 90000, description = {}, model = "pcj"},
				{name = "Zombie Chobber", costs = 385000, description = {}, model = "zombieb"},
				{name = "Vindicator", costs = 600000, description = {}, model = "vindicator"},
				{name = "Sanchez", costs = 100000, description = {}, model = "sanchez"},
				{name = "Nightblade", costs = 400000, description = {}, model = "nightblade"},
			}
		},
	}
}

return vehshop